class SquatDetectionConfig {
  const SquatDetectionConfig({
    this.calibrationDurationUs = 1200000,
    this.minimumCalibrationFrames = 24,
    this.maximumCalibrationHipRange = 0.03,
    this.maximumCalibrationAngleRange = 12,
    this.landmarkConfidenceFloor = 0.35,
    this.aggregateConfidenceFloor = 0.35,
    this.descentKneeFlexDegrees = 8,
    this.descentHipFlexDegrees = 7,
    this.descentHipDrop = 0.025,
    this.descentVelocity = 0.08,
    this.minimumIntentKneeFlexDegrees = 25,
    this.minimumIntentHipFlexDegrees = 20,
    this.minimumIntentHipDropWithKnee = 0.06,
    this.minimumIntentHipDropWithHip = 0.08,
    this.bottomVelocity = 0.04,
    this.ascentVelocity = -0.08,
    this.standingKneeFlexDegrees = 14,
    this.standingHipFlexDegrees = 12,
    this.standingHipDrop = 0.04,
    this.directionDwellUs = 90000,
    this.completionDwellUs = 100000,
    this.refractoryUs = 400000,
    this.shortTrackingHoldUs = 250000,
    this.trackingLostUs = 500000,
    this.reacquireStandingUs = 300000,
    this.maximumAttemptUs = 12000000,
    this.maximumJointAngularVelocityDegreesPerSecond = 720,
    this.maximumHipDropVelocity = 2.5,
  });

  final int calibrationDurationUs;
  final int minimumCalibrationFrames;
  final double maximumCalibrationHipRange;
  final double maximumCalibrationAngleRange;
  final double landmarkConfidenceFloor;
  final double aggregateConfidenceFloor;
  final double descentKneeFlexDegrees;
  final double descentHipFlexDegrees;
  final double descentHipDrop;
  final double descentVelocity;
  final double minimumIntentKneeFlexDegrees;
  final double minimumIntentHipFlexDegrees;
  final double minimumIntentHipDropWithKnee;
  final double minimumIntentHipDropWithHip;
  final double bottomVelocity;
  final double ascentVelocity;
  final double standingKneeFlexDegrees;
  final double standingHipFlexDegrees;
  final double standingHipDrop;
  final int directionDwellUs;
  final int completionDwellUs;
  final int refractoryUs;
  final int shortTrackingHoldUs;
  final int trackingLostUs;
  final int reacquireStandingUs;
  final int maximumAttemptUs;
  final double maximumJointAngularVelocityDegreesPerSecond;
  final double maximumHipDropVelocity;
}
